certs:
  kafka:
    cert:
    key:
oauth:
  clientId: 
  issuer: 
  jwksEndpoint:
  subClaim: sub
  tlsTrustedCert:
  disableTlsHostnameVerification: false
tenancy: Shared
tolerations: []
nodeAffinity:
domain:
strimzi:
  version: latest
kafka:
  version: 4.1.1
  diskSize: 100Gi
  listeners:
    external: 
      enabled: true
    internal: 
      enabled: true
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  tieredStorage:
    enabled: true # Set to true for backwards compatibility
    provider: S3
    cloud: aws
    bucketName: 
    endpoint: 
    aws:
      accessKey:
      secretKey:
      region:
kraft:
  diskSize: 50Gi
replicas: 3