apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth
consumerRef: streamtime-agent
config: 
  key_names:
    - apikey
  hide_credentials: false
  key_in_header: true
plugin: key-auth