apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: streamtime-agent
  annotations:
    kubernetes.io/ingress.class: kong
username: streamtime-agent
credentials:
  - streamtime-agent-apikey