apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: secure-response-headers
instance_name: secure-response-headers
config:
  remove:
    headers:
      - Server
      - X-Powered-By
  add:
    headers:
      - Strict-Transport-Security:max-age=63072000;includeSubDomains;preload
      - X-Frame-Options:DENY
      - X-Content-Type-Options:nosniff
plugin: response-transformer
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cache-response-headers
instance_name: cache-response-headers
config:
  add:
    headers:
      - Cache-Control:nostore, must-revalidate
plugin: response-transformer
