{{- if eq .Values.sourceCluster.authentication.type "tls" }}
{{- if and .Values.sourceCluster.authentication.tls.certificateContent .Values.sourceCluster.authentication.tls.keyContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamtime-mirrormaker.sourceAuthSecretName" . }}
type: Opaque
stringData:
  tls.crt: {{ .Values.sourceCluster.authentication.tls.certificateContent }}
  tls.key: {{ .Values.sourceCluster.authentication.tls.keyContent }}
{{- end }}
{{- end }}

{{- if eq .Values.sourceCluster.authentication.type "scram-sha-256" }}
{{- if and .Values.sourceCluster.authentication.scramSha256.username .Values.sourceCluster.authentication.scramSha256.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamtime-mirrormaker.sourceAuthSecretName" . }}
type: Opaque
stringData:
  password: {{ .Values.sourceCluster.authentication.scramSha256.password }}
{{- end }}
{{- end }}

{{- if eq .Values.sourceCluster.authentication.type "scram-sha-512" }}
{{- if and .Values.sourceCluster.authentication.scramSha512.username .Values.sourceCluster.authentication.scramSha512.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamtime-mirrormaker.sourceAuthSecretName" . }}
type: Opaque
stringData:
  password: {{ .Values.sourceCluster.authentication.scramSha512.password }}
{{- end }}
{{- end }}

{{- if eq .Values.sourceCluster.authentication.type "plain" }}
{{- if and .Values.sourceCluster.authentication.plain.username .Values.sourceCluster.authentication.plain.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamtime-mirrormaker.sourceAuthSecretName" . }}
type: Opaque
stringData:
  password: {{ .Values.sourceCluster.authentication.plain.password }}
{{- end }}
{{- end }}

{{- if eq .Values.sourceCluster.authentication.type "oauth" }}
{{- if and .Values.sourceCluster.authentication.oauth.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamtime-mirrormaker.sourceAuthSecretName" . }}
type: Opaque
stringData:
  clientSecret: {{ .Values.sourceCluster.authentication.oauth.clientSecret }}
{{- end }}
{{- end }}
