{{- if and .Values.certs.kafka.cert .Values.certs.ca.cert  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-clusterlink-source-tls
type: Opaque
data:
  cacerts.pem: {{ .Values.certs.ca.cert | b64enc | quote }}
  fullchain.pem: {{ .Values.certs.kafka.cert | b64enc | quote }}
{{- end }}