apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cl-src-cred
type: Opaque
data:
  plain-jaas.conf: {{ printf "sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username='%s'   password='%s';" .Values.source.credentials.username .Values.source.credentials.password | b64enc }}