{{- if .Values.remoteWrite.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: remote-write-credentials
  namespace: {{ .Values.prometheus.namespace }}
stringData:
  client_id: {{ .Values.remoteWrite.credentials.clientId }}
  client_secret: {{ .Values.remoteWrite.credentials.clientSecret }}
{{- end }}

