certs:
  cert:
  key:
oauth_jwks_uri:
oauth_issuer:
opencost:
  hostname: 
  username: 
  password: 
  service: kafka-fleet-manager-opencost
  namespace: opencost
  # path: /opencost
prometheus:
  hostname:
  username:
  password:
  service: kafka-fleet-manager-promet-prometheus
  namespace: monitoring
  # path: /prometheus
alertmanager:
  hostname:
  username:
  password:
  service: kafka-fleet-manager-promet-alertmanager
  # path: /alerts
alertmanagerConfig:
  name:
  webhookUrl:
  receivers: []
loki:
  hostname:
  service: kafka-fleet-manager-loki-gateway
  # path: /loki
strimzi:
  namespace: strimzi
domain:
certManager:
  namespace: cert-manager
  route53:
    region:
    hostedZoneID:
    accessKeyID:
    secretAccessKey:
externalDns:
  namespace: external-dns
  route53:
    accessKeyID:
    secretAccessKey:
remoteWrite:
  enabled: false
  credentials:
    clientId:
    clientSecret: